### ISSUE TITLE
python.ipynb.html' not found.

### ISSUE THREAD

**Issue by fjp** [red-data-tools/jekyll-jupyter-notebook#6] opened 2018-07-11 20:38 UTC
Hi,

thanks for the gem. However, I always get the following error:

> Not Found
> `/test/python.ipynb.html' not found.
> WEBrick/1.4.2 (Ruby/2.5.1/2018-03-29) at localhost:4000

I placed the python.ipynb file inside the same folder as test.md.
Do I need to first export the ipython notebook as html manually?

**Comment by kou** [comment] 2018-07-12 07:30
Can you show your repository that reprouces this case and how to reproduce this case with the repository?

**Comment by fjp** [comment] 2018-07-12 20:21
Currently I am testing it only local with the [minimal mistakes](https://github.com/mmistakes/minimal-mistakes/tree/master/test) jekyll theme. Later I wanted to host it on github but I guess this won't be possible anyway because the gem is not on the whitelist of github pages. 

When I create a new post inside the _posts folder including the python.ipynb file and use the include tag, I get the error message when I want to display the post:

> Not Found
> `/ipython/python.ipynb.html' not found.
> WEBrick/1.4.2 (Ruby/2.5.1/2018-03-29) at localhost:4000

When I save the notebook as python.ipynb.html in a new folder (at the root dir) /ipython everything gets displayed as expected.

A similar thing happens when I want to create a new page inside the _pages folder. Then I get the following message (see also my first post, its the same):

> Not Found
> `/test/python.ipynb.html' not found.
> WEBrick/1.4.2 (Ruby/2.5.1/2018-03-29) at localhost:4000

This can be solved again by adding a folder test.

I am quite new to Jekyll and don't know how to fix this path issue. Has this something to do with how minimal mistakes works?

**Comment by kou** [comment] 2018-07-13 02:48
Can you upload your test files and share it?

**Comment by fjp** [comment] 2018-07-16 18:27
The post inside _posts/2018-07-11-ipython.md contains:

```
---
layout: single
title:  "IPython"
date:   2018-07-11 20:10:12 +0200
toc: true
---

## Top page

Here is a Jupyter Notebook:

{% jupyter_notebook python.ipynb %}

### Raw rendered pages

  * [Raw IPython kernel](python-raw.html)

### Other kernels

  * [IRuby kernel](ruby/)
```

Inside the _posts folder I also have the python.ipynb notebook that contains nothing special except some python code.

The post shows up but displays the the following output/error:

![image](https://user-images.githubusercontent.com/1286618/42776080-4e0267c6-8936-11e8-80a9-686b0b6cbbde.png)


I also tried a page test/test.md with the following content:

```
---
layout: default
title: Top
permalink: /test/
---

## Top page

Here is a Jupyter Notebook:

{% jupyter_notebook python.ipynb %}

### Raw rendered pages

  * [Raw IPython kernel](python-raw.html)

### Other kernels

  * [IRuby kernel](ruby/)
```

This gives a similar output:

![image](https://user-images.githubusercontent.com/1286618/42776188-920d2ee2-8936-11e8-96cb-4a4f73ca912c.png)

**Comment by kou** [comment] 2018-07-17 00:41
I close this issue because you don't provide all files. For example, you don't provide `python.ipynb`, `Gemfile` and so on.
I hoped that you provide a repository that contains all files to reproduce this case.

https://github.com/red-data-tools/jekyll-jupyter-notebook/tree/master/example will help you.

**Closed by kou** 2018-07-17 00:41 UTC

**Comment by fjp** [comment] 2018-07-17 19:37
Sorry for not providing the files. I did not do that because the gem is not working with github pages. 
However, I uploaded it anyway. You can see the repo here:
[https://github.com/fjp/fjp.github.io](https://github.com/fjp/fjp.github.io)

And here is the [link](https://fjp.github.io/blog/) where the ipython post is missing because of a build error on github:

> The page build failed for the `master` branch with the following error:
> 
> The tag `jupyter_notebook` on line 5 in `_posts/2018-07-11-ipython.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.
> 
> 
> 
> When I run this site locally using the following command

Locally I testes with the following command and got the results described above.

`DISABLE_WHITELIST=true bundle exec jekyll serve`

**Comment by fjp** [comment] 2018-07-17 19:42
Thanks for providing the example I will also try to spot the error why I cannot properly display post which include a jupyter notebook locally.

By comparing the example Gemfile you provided with mine, I saw that the line where the gem is included has an additional path (option?). Is this required?
gem "jekyll-jupyter-notebook", path: ".."
